# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Juliette Caucheteux"
title_separator          : "-"
name                     : &name "Juliette Caucheteux"
description              : &description "personal description"
url                      : https://juliettecx.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "https://juliettecx.github.io"
author                   : "Juliette Caucheteux"
top_panel_links:
  - name: "CV"
    url: "/cv/"
  - name: "Research"
    url: "/research/"
  - name: "Miscellaneous"
    url: "/miscellaneous/"
