# Basic Site Settings
locale: "en-US"
title: "Juliette Caucheteux"
title_separator: "-"
name: &name "Juliette Caucheteux"
description: &description "personal description"
url: https://juliettecx.github.io  # Base hostname & protocol for your site
baseurl: ""  # Subpath of your site, e.g. "/blog"
repository: "https://juliettecx.github.io"
author: "Juliette Caucheteux"
email: "juliette.caucheteux@some.ox.ac.uk"
institution: University of Oxford, Somerville College

# Include _pages directory
include:
  - _pages

# Default settings for pages
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/

# Top panel links for navigation
top_panel_links:
  - name: "Home"
    url: "/"
  - name: "CV"
    url: "/cv/"
  - name: "Research"
    url: "/research/"
  - name: "Miscellaneous"
    url: "/miscellaneous/"
    sublinks:
      - name: "Recipes"
        url: "/miscellaneous/recipes/"
      - name: "Salty"
        url: "/miscellaneous/salty/"
    
